### ISSUE TITLE
Objetos comunes a todo el juego

### ISSUE THREAD

**Issue by fedesanches** [GauchoGSDMS/DeadManSteps#1]
A continuacion detallo los objetos que son comunes a todos los niveles del juego y por  que propongo comenzar a modelar:

- [ ] Arbol forma de pino
- [ ] Arbol pequeño con maseta
- [ ] Escritorio de madera
- [x] Silla de madera
